server:
  port: 8081

spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: desk-service
      auto-offset-reset: earliest
    producer:
      retries: 0
    template:
      send-topic: desk-to-customer
      receive-topic: customer-to-desk

logging:
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 1
