spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
#    password: postgres
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/desk
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: desk-service
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring:
#          deserializer:
#            value:
#              delegate: org.springframework.kafka.support.serializer.JsonDeserializer
#            producer:
#              key-serializer: org.apache.kafka.common.serialization.StringSerializer
#              value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 1
