logging:
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 1



spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}

  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: customer-service
      auto-offset-reset: earliest
    producer:
      retries: 0
    template:
      send-topic: customer-to-desk
      receive-topic: desk-to-customer

security:
  secret-key: F/tfR/hN4CIkrsg6OHPT5ZfMJH0wPVzr9NPCZtD62Mw=
  expiration: 60480000


