services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: desk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

#

  customer-service:
    build:
      context: ./customer
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/desk
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  desk-service:
    build:
      context: ./desk
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/desk
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"
    networks:
      - app-network
    restart: always

  #   pgadmin:
  #    container_name: ms_pgadmin
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: postgres@example.com
  #      PGADMIN_DEFAULT_PASSWORD: postgres
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #      volumes:
  #        - pgadmin:/var/lib/pgadmin
  #      ports:
  #        - "5050:80"
  #      networks:
  #        - app-network
  #      restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
#  pgadmin:







