server:
  port: 8080

spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  secret-key: F/tfR/hN4CIkrsg6OHPT5ZfMJH0wPVzr9NPCZtD62Mw=
  expiration: 60480000 #miliseconds


